name: "Elyseum Coverage Reporter"
description: "Installs elyseum-cli, runs it, and comments on a PR with the results"
inputs:
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false
  github_token_actor:
    description: 'The name of the GitHub app that owns the GitHub API Access Token (see github_token). Used to identify pull request comments created by this action during earlier runs. Has to be set when `github_token` is set to a GitHub app installation token (other than GitHub actions). Otherwise, existing comments will not be updated, but new comments created. Note: this does not change the bot name of the pull request comments. Defaults to "github-actions".'
    default: 'github-actions'
    required: false
  command:
    description: "Command to run elyseum-cli with (diff-coverage, coverage, etc.)"
    default: "diff-coverage"
  comment-name:
    description: "Name of the comment to update or create"
    default: "Elyseum Coverage Reporter"
  workdir:
    description: "Working directory to run elyseum-cli in"
    default: "."
  quality-gate:
    description: "Quality gate to check against"
    default: "80"
  quality-gate-fail:
    description: "Quality gate to fail against"
    default: "50"
  use-dev-elyseum-cli:
    description: "Use the development version of elyseum-cli"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install elyseum-cli
      if: ${{ inputs.use-dev-elyseum-cli == 'false' }}
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: npm install -g @dragonshorn-studios/elyseum-cli
    
    - name: Install elyseum-cli from Dragonshorn-Studios/elyseum-cli repository
      if: ${{ inputs.use-dev-elyseum-cli == 'true' }}
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        git clone https://github.com/Dragonshorn-Studios/elyseum-cli.git /tmp/elyseum-cli
        cd /tmp/elyseum-cli
        npm install
        npm link .

    - name: Run elyseum-cli
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: elyseum-cli ${{ inputs.command }} --reporter.coverage=github-pr-comment --reporter.coverage.github-pr-comment.comment-name "${{ inputs.comment-name }}" --reporter.coverage.github-pr-comment.create-annotations --reporter.coverage.github-pr-comment.quality-gate "${{ inputs.quality-gate }}" --reporter.coverage.github-pr-comment.quality-gate-fail "${{ inputs.quality-gate-fail }}"
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}

